# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# cannot extract pack cache, as it's using a named volume

variables:
  ArtifactFeed: 6ebc2d9e-a94e-416e-b463-fea4fdb4ffb8

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ls -al
- script: |
    mvn clean package -DskipTests
    jarfile=`find ./target -name *.jar`
    echo FROM java:8 \
    WORKDIR /app \
    COPY . /app \
    ADD $jarfile /app/demo.jar \
    EXPOSE 8080 \
    ENTRYPOINT ["java","-jar","/app/demo.jar"] \
    > Dockerfile
    docker login -u normanch -p "${pswd}"
    docker push normanch/spring-demo-test
    docker run --restart=always --name demo -p 8080:8080 normanch/spring-demo-test
  env:
    pswd: $(dockerPassword)
- script: |
    ls -al
